[package]
name = "fitness-api"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = "4.5.1"
reqwest = "0.11.24"
tokio = { version = "1.36.0", features = ["rt", "macros", "rt-multi-thread"] }
