/* tslint:disable */
/* eslint-disable */
export const memory: WebAssembly.Memory;
export function login(a: number, b: number, c: number, d: number, e: number, f: number): number;
export function courses(a: number, b: number, c: number, d: number): number;
export function slots(a: number, b: number, c: number, d: number): number;
export function book_course(a: number, b: number, c: number, d: number, e: number, f: number): number;
export function __wbg_netpulseloginresponse_free(a: number): void;
export function __wbg_get_netpulseloginresponse_user_id(a: number, b: number): void;
export function __wbg_set_netpulseloginresponse_user_id(a: number, b: number, c: number): void;
export function __wbg_get_netpulseloginresponse_first_name(a: number, b: number): void;
export function __wbg_set_netpulseloginresponse_first_name(a: number, b: number, c: number): void;
export function __wbg_get_netpulseloginresponse_last_name(a: number, b: number): void;
export function __wbg_set_netpulseloginresponse_last_name(a: number, b: number, c: number): void;
export function __wbg_get_netpulseloginresponse_verified(a: number): number;
export function __wbg_set_netpulseloginresponse_verified(a: number, b: number): void;
export function __wbg_get_netpulseloginresponse_email_varified(a: number): number;
export function __wbg_set_netpulseloginresponse_email_varified(a: number, b: number): void;
export function __wbg_get_netpulseloginresponse_club_id(a: number, b: number): void;
export function __wbg_set_netpulseloginresponse_club_id(a: number, b: number, c: number): void;
export function __wbg_get_netpulseloginresponse_club_name(a: number, b: number): void;
export function __wbg_set_netpulseloginresponse_club_name(a: number, b: number, c: number): void;
export function __wbg_get_netpulseloginresponse_chain_uuid(a: number, b: number): void;
export function __wbg_set_netpulseloginresponse_chain_uuid(a: number, b: number, c: number): void;
export function __wbg_get_netpulseloginresponse_chain_name(a: number, b: number): void;
export function __wbg_set_netpulseloginresponse_chain_name(a: number, b: number, c: number): void;
export function __wbg_get_netpulseloginresponse_timezone(a: number, b: number): void;
export function __wbg_set_netpulseloginresponse_timezone(a: number, b: number, c: number): void;
export function __wbg_get_netpulseloginresponse_timezone_offset(a: number): number;
export function __wbg_set_netpulseloginresponse_timezone_offset(a: number, b: number): void;
export function __wbg_get_netpulseloginresponse_profile_completed(a: number): number;
export function __wbg_set_netpulseloginresponse_profile_completed(a: number, b: number): void;
export function __wbg_get_netpulseloginresponse_membership_type(a: number, b: number): void;
export function __wbg_set_netpulseloginresponse_membership_type(a: number, b: number, c: number): void;
export function __wbg_bookingrequest_free(a: number): void;
export function __wbg_get_bookingrequest_user_id(a: number): number;
export function __wbg_set_bookingrequest_user_id(a: number, b: number): void;
export function __wbg_get_bookingrequest_slot_id(a: number): number;
export function __wbg_set_bookingrequest_slot_id(a: number, b: number): void;
export function __wbg_get_bookingrequest_course_id(a: number): number;
export function __wbg_set_bookingrequest_course_id(a: number, b: number): void;
export function create_booking_request(a: number, b: number, c: number, d: number, e: number, f: number): number;
export function __wbg_simplecourse_free(a: number): void;
export function __wbg_get_simplecourse_id(a: number): number;
export function __wbg_set_simplecourse_id(a: number, b: number): void;
export function __wbg_get_simplecourse_title(a: number, b: number): void;
export function __wbg_set_simplecourse_title(a: number, b: number, c: number): void;
export function __wbg_get_simplecourse_typ(a: number, b: number): void;
export function __wbg_set_simplecourse_typ(a: number, b: number, c: number): void;
export function __wbg_get_simplecourse_duration(a: number): number;
export function __wbg_set_simplecourse_duration(a: number, b: number): void;
export function __wbg_get_simplecourse_category(a: number, b: number): void;
export function __wbg_set_simplecourse_category(a: number, b: number, c: number): void;
export function __wbg_get_simplecourse_description(a: number, b: number): void;
export function __wbg_set_simplecourse_description(a: number, b: number, c: number): void;
export function __wbg_get_simplecourse_image_url(a: number, b: number): void;
export function __wbg_set_simplecourse_image_url(a: number, b: number, c: number): void;
export function __wbg_get_simplecourse_bookable(a: number): number;
export function __wbg_set_simplecourse_bookable(a: number, b: number): void;
export function __wbg_get_coursewrapper_course(a: number): number;
export function __wbg_set_coursewrapper_course(a: number, b: number): void;
export function __wbg_coursewithslot_free(a: number): void;
export function __wbg_get_coursewithslot_id(a: number, b: number): void;
export function __wbg_set_coursewithslot_id(a: number, b: number, c: number): void;
export function __wbg_get_coursewithslot_name(a: number, b: number): void;
export function __wbg_set_coursewithslot_name(a: number, b: number, c: number): void;
export function __wbg_get_coursewithslot_start_date_time(a: number): number;
export function __wbg_set_coursewithslot_start_date_time(a: number, b: number): void;
export function __wbg_get_coursewithslot_end_date_time(a: number): number;
export function __wbg_set_coursewithslot_end_date_time(a: number, b: number): void;
export function __wbg_get_coursewithslot_max_capacity(a: number): number;
export function __wbg_set_coursewithslot_max_capacity(a: number, b: number): void;
export function __wbg_get_coursewithslot_booked(a: number): number;
export function __wbg_set_coursewithslot_booked(a: number, b: number): void;
export function __wbg_get_coursewithslot_total_booked(a: number): number;
export function __wbg_set_coursewithslot_total_booked(a: number, b: number): void;
export function __wbg_coursewrapper_free(a: number): void;
export const __wbindgen_export_0: WebAssembly.Table;
export function _dyn_core__ops__function__FnMut__A____Output___R_as_wasm_bindgen__closure__WasmClosure___describe__invoke__hc1c4f16c3a7d8f72(a: number, b: number, c: number): void;
export function __wbindgen_malloc(a: number, b: number): number;
export function __wbindgen_realloc(a: number, b: number, c: number, d: number): number;
export function __wbindgen_exn_store(a: number): void;
export function __wbindgen_add_to_stack_pointer(a: number): number;
export function __wbindgen_free(a: number, b: number, c: number): void;
export function wasm_bindgen__convert__closures__invoke2_mut__h4289acb35cbe71a1(a: number, b: number, c: number, d: number): void;
