[package]
name = "lambda-common"
version = "0.1.0"
edition = "2021"

[dependencies]
booking-first-lib = { path = "../booking-first-lib" }
shared = { path = "../shared" }
reqwest = { version = "0.11.26", default-features = false, features = ["rustls-tls"] }
